export const States: {
  name: string;
  latitude: number;
  longitude: number;
  logoUrl: string;
}[] = [
  {
    name: "Abia",
    latitude: 5.4167,
    longitude: 7.5,
    logoUrl: "https://example.com/abia_logo.jpg",
  },
  {
    name: "Adamawa",
    latitude: 9.3333,
    longitude: 12.5,
    logoUrl: "https://example.com/adamawa_logo.jpg",
  },
  {
    name: "Akwa Ibom",
    latitude: 5,
    longitude: 7.5,
    logoUrl: "https://example.com/akwa_ibom_logo.jpg",
  },
  {
    name: "Anambra",
    latitude: 6.3333,
    longitude: 7.1667,
    logoUrl: "https://example.com/anambra_logo.jpg",
  },
  {
    name: "Bauchi",
    latitude: 10.5,
    longitude: 10,
    logoUrl: "https://example.com/bauchi_logo.jpg",
  },
  {
    name: "Bayelsa",
    latitude: 4.75,
    longitude: 6,
    logoUrl: "https://example.com/bayelsa_logo.jpg",
  },
  {
    name: "Benue",
    latitude: 7.3333,
    longitude: 8.75,
    logoUrl: "https://example.com/benue_logo.jpg",
  },
  {
    name: "Borno",
    latitude: 12,
    longitude: 13,
    logoUrl: "https://example.com/borno_logo.jpg",
  },
  {
    name: "Cross River",
    latitude: 5.75,
    longitude: 8.5,
    logoUrl: "https://example.com/cross_river_logo.jpg",
  },
  {
    name: "Delta",
    latitude: 5.5,
    longitude: 5.75,
    logoUrl: "https://example.com/delta_logo.jpg",
  },
  {
    name: "Ebonyi",
    latitude: 6.25,
    longitude: 8,
    logoUrl: "https://example.com/ebonyi_logo.jpg",
  },
  {
    name: "Edo",
    latitude: 6.5,
    longitude: 6.5,
    logoUrl: "https://example.com/edo_logo.jpg",
  },
  {
    name: "Ekiti",
    latitude: 8,
    longitude: 5.25,
    logoUrl: "https://example.com/ekiti_logo.jpg",
  },
  {
    name: "Enugu",
    latitude: 6.5,
    longitude: 7.5,
    logoUrl: "https://example.com/enugu_logo.jpg",
  },
  {
    name: "Gombe",
    latitude: 10.4167,
    longitude: 11,
    logoUrl: "https://example.com/gombe_logo.jpg",
  },
  {
    name: "Imo",
    latitude: 5.4833,
    longitude: 7,
    logoUrl: "https://example.com/imo_logo.jpg",
  },
  {
    name: "Jigawa",
    latitude: 12,
    longitude: 9.5,
    logoUrl: "https://example.com/jigawa_logo.jpg",
  },
  {
    name: "Kaduna",
    latitude: 10.5,
    longitude: 8,
    logoUrl: "https://example.com/kaduna_logo.jpg",
  },
  {
    name: "Kano",
    latitude: 12,
    longitude: 8.5,
    logoUrl: "https://example.com/kano_logo.jpg",
  },
  {
    name: "Katsina",
    latitude: 12.5,
    longitude: 7.5,
    logoUrl: "https://example.com/katsina_logo.jpg",
  },
  {
    name: "Kebbi",
    latitude: 11.5,
    longitude: 4.5,
    logoUrl: "https://example.com/kebbi_logo.jpg",
  },
  {
    name: "Kogi",
    latitude: 8.75,
    longitude: 7.5,
    logoUrl: "https://example.com/kogi_logo.jpg",
  },
  {
    name: "Kwara",
    latitude: 8.5,
    longitude: 4.5,
    logoUrl: "https://example.com/kwara_logo.jpg",
  },
  {
    name: "Lagos",
    latitude: 6.5244,
    longitude: 3.3792,
    logoUrl: "https://example.com/lagos_logo.jpg",
  },
  {
    name: "Nasarawa",
    latitude: 8.5,
    longitude: 8,
    logoUrl: "https://example.com/nasarawa_logo.jpg",
  },
  {
    name: "Niger",
    latitude: 10.5,
    longitude: 6,
    logoUrl: "https://example.com/niger_logo.jpg",
  },
  {
    name: "Ogun",
    latitude: 7,
    longitude: 3.5,
    logoUrl: "https://example.com/ogun_logo.jpg",
  },
  {
    name: "Ondo",
    latitude: 7,
    longitude: 5.5,
    logoUrl: "https://example.com/ondo_logo.jpg",
  },
  {
    name: "Osun",
    latitude: 7.5,
    longitude: 4.5,
    logoUrl: "https://example.com/osun_logo.jpg",
  },
  {
    name: "Oyo",
    latitude: 8,
    longitude: 4,
    logoUrl: "https://example.com/oyo_logo.jpg",
  },
  {
    name: "Plateau",
    latitude: 10,
    longitude: 9,
    logoUrl: "https://example.com/plateau_logo.jpg",
  },
  {
    name: "Rivers",
    latitude: 4.75,
    longitude: 7,
    logoUrl: "https://example.com/rivers_logo.jpg",
  },
  {
    name: "Sokoto",
    latitude: 13,
    longitude: 5,
    logoUrl: "https://example.com/sokoto_logo.jpg",
  },
  {
    name: "Sokoto",
    latitude: 13.0833,
    longitude: 5.2333,
    logoUrl: "https://example.com/sokoto_logo.jpg",
  },
  {
    name: "Taraba",
    latitude: 8.9167,
    longitude: 11.3667,
    logoUrl: "https://example.com/taraba_logo.jpg",
  },
  {
    name: "Yobe",
    latitude: 12,
    longitude: 11.5,
    logoUrl: "https://example.com/yobe_logo.jpg",
  },
  {
    name: "Zamfara",
    latitude: 12.1667,
    longitude: 6.6667,
    logoUrl: "https://example.com/zamfara_logo.jpg",
  },
];
